/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Account credential, bytes in base64
 *
 * This interface was referenced by `AccMan`'s JSON-Schema
 * via the `definition` "credential".
 */
export type Credential = string;
/**
 * An amount, positive or negative, in digits
 *
 * This interface was referenced by `AccMan`'s JSON-Schema
 * via the `definition` "amount".
 */
export type Amount = string;
/**
 * tot response
 *
 * This interface was referenced by `AccMan`'s JSON-Schema
 * via the `definition` "totRes".
 */
export type TotRes = string;

/**
 * A simple account manager
 */
export interface AccMan {
  [k: string]: unknown;
}
/**
 * tot query string
 *
 * This interface was referenced by `AccMan`'s JSON-Schema
 * via the `definition` "totQuery".
 */
export interface TotQuery {
  cred: Credential;
}
/**
 * mod query string
 *
 * This interface was referenced by `AccMan`'s JSON-Schema
 * via the `definition` "modQuery".
 */
export interface ModQuery {
  cred: Credential;
  /**
   * An amount, positive or negative, in digits
   */
  by: string;
}
